### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by ItsEntDev** [trolljoe/joefetch#1]
**Is your feature request related to a problem? Please describe.**
Windows support. Make it so it supports Windows (not WSL that's boring).

**Describe the solution you'd like**
I want you, one Mr. Joetroll, to add support for the Windows NT 10.0+ Operating System.

**Describe alternatives you've considered**
Not use it, but that's lame

**Additional context**
Wicrosoft Mindows

**Comment by trolljoe** [comment]
open a pull request lazy
